version: "3.3"

services:
  db:
    image: mysql
    container_name: ${ENVIRONMENT}-db
    restart: on-failure
    env_file:
      - ${ENVIRONMENT}.env
    ports:
    - '3306:3306'
    expose:
    - '3306'
    volumes:
    - db:/var/lib/${ENVIRONMENT}-mysql

volumes:
  db: