version: "3.3"

services:
  db:
    image: mysql
    restart: always
    env_file:
      - ${ENVIRONMENT_FILE}
    ports:
    - '3306:3306'
    expose:
    - '3306'
    volumes:
    - db:/var/lib/mysql

volumes:
  db: